name: main-workflow
on: [push]
jobs:
  build_package:
    runs-on: ubuntu-latest
    container:
      image: daugraph/tensorflow-dev:0.5.0
    steps:
      - uses: actions/checkout@v3
      - run: |
        echo "start local server for compile"
        ls -al
        cd local_server
        nohup python local_server.py &
      - run: |
        echo "configure and build"
        export TF_NEED_CUDA=0
        export PYTHON_BIN_PATH=/usr/local/bin/python
        ./configure
        bazel build --jobs 2 -c opt tensorflow/tools/pip_package:build_pip_package
      - run: |
        echo "install package"
        rm -rf /tmp/pip/*
        bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/pip
        ls -al /tmp/pip/
        pip install --upgrade --no-deps --force-reinstall /tmp/pip/*.whl
      - uses: actions/upload-artifact@v3
        with:
          name: tensorflow-dev
          path: /tmp/pip/*.whl
      