name: main-workflow
on: [push]
jobs:
  build_package:
    runs-on: ubuntu-latest
    container:
      image: daugraph/tensorflow-dev:0.5.0
    steps:
      - uses: actions/checkout@v3
      - run: cd local_server && nohup python local_server.py &
      - run: export TF_NEED_CUDA=0
      - run: export PYTHON_BIN_PATH=$(which python)
      - run: ./configure
      - run: bazel build --jobs 2 -c opt tensorflow/tools/pip_package:build_pip_package
      - run: bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/pip
      - run: ls -al /tmp/pip/
      - run: pip install --upgrade --no-deps --force-reinstall /tmp/pip/*.whl
      - uses: actions/upload-artifact@v3
        with:
          name: tensorflow-dev
          path: /tmp/pip/*.whl
      
