name: main-workflow
on: [push]
jobs:
  build_package:
    runs-on: ubuntu-latest
    container:
      image: daugraph/tensorflow-dev:0.6.0
    steps:
      - run: cd local_server
      - run: nohup bash local_server.sh &
