name: main-workflow
on: [push]
jobs:
  build_package:
    runs-on: ubuntu-latest
    container:
      image: daugraph/tensorflow-dev:0.6.0
    steps:
      - run: eval 'ls -al'
      - uses: actions/checkout@v3
      - run: eval 'ls -al'
      - run: cd local_server && bash local_server.sh
