name: main-workflow
on: [push]
jobs:
  build_package:
    runs-on: ubuntu-latest
    container:
      image: daugraph/tensorflow-dev:0.6.1
    steps:
      - uses: actions/checkout@v3
      - run: eval 'ls -al'
      - run: cd local_server && nohup python local_server.py &
      - run: bazel build -c opt tensorflow/tools/pip_package:build_pip_package
